import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import fs from "node:fs";
import path from "node:path";

const db = new PrismaClient();

/**
 * Simple script to link existing students to groups via StudentGroup records.
 * This solves the attendance page showing "0 students" issue.
 */

async function main() {
  console.log("🔗 Linking students to groups...\n");

  try {
    // Read the student_group_links.csv that was generated by import-excel
    const linksPath = path.join(
      process.cwd(),
      "docs",
      "generated-import",
      "student_group_links.csv",
    );

    if (!fs.existsSync(linksPath)) {
      console.error(`❌ File not found: ${linksPath}`);
      console.error(
        "   Run: npm run import:excel -- <path-to-excel-file> first",
      );
      process.exit(1);
    }

    const fileContent = fs.readFileSync(linksPath, "utf-8");
    const lines = fileContent.split("\n").filter((line) => line.trim());

    if (lines.length < 2) {
      console.error("❌ CSV file is empty or invalid");
      process.exit(1);
    }

    // Parse CSV (skip header)
    const links: Array<{ phone: string; groupName: string }> = [];
    for (let i = 1; i < lines.length; i++) {
      const [phone, groupName] = lines[i]
        .split(",")
        .map((s) => s.trim().replace(/^"(.*)"$/, "$1"));
      if (phone && groupName) {
        links.push({ phone, groupName });
      }
    }

    console.log(`📋 Found ${links.length} student-group links to create\n`);

    let linked = 0;
    let skipped = 0;
    const errors: string[] = [];

    for (const link of links) {
      try {
        // Find student by phone or parent phone
        const student = await db.student.findFirst({
          where: {
            OR: [
              { phone: { equals: link.phone, mode: "insensitive" } },
              { parentPhone: { equals: link.phone, mode: "insensitive" } },
            ],
          },
          select: { id: true, firstName: true, lastName: true },
        });

        if (!student) {
          errors.push(`❌ Student not found with phone: ${link.phone}`);
          skipped += 1;
          continue;
        }

        // Find group by name
        const group = await db.group.findFirst({
          where: {
            OR: [
              { name: { equals: link.groupName, mode: "insensitive" } },
              // Also match with "Group" suffix
              {
                name: {
                  equals: link.groupName + " Group",
                  mode: "insensitive",
                },
              },
            ],
          },
          select: { id: true, name: true },
        });

        if (!group) {
          errors.push(`❌ Group not found: ${link.groupName}`);
          skipped += 1;
          continue;
        }

        // Check if link already exists
        const existingLink = await db.groupStudent.findUnique({
          where: {
            groupId_studentId: {
              groupId: group.id,
              studentId: student.id,
            },
          },
        });

        if (existingLink) {
          if (existingLink.leftAt) {
            // Reactivate the link
            await db.groupStudent.update({
              where: { id: existingLink.id },
              data: { leftAt: null },
            });
            console.log(
              `✓ Reactivated: ${student.firstName} ${student.lastName} → ${group.name}`,
            );
            linked += 1;
          } else {
            skipped += 1;
          }
          continue;
        }

        // Create new link
        await db.groupStudent.create({
          data: {
            groupId: group.id,
            studentId: student.id,
            joinedAt: new Date(),
          },
        });

        console.log(
          `✓ Linked: ${student.firstName} ${student.lastName} → ${group.name}`,
        );
        linked += 1;
      } catch (error) {
        errors.push(
          `❌ Error linking ${link.phone}: ${error instanceof Error ? error.message : String(error)}`,
        );
        skipped += 1;
      }
    }

    console.log("\n" + "=".repeat(60));
    console.log(`✅ Linking complete!`);
    console.log(`   Linked: ${linked}`);
    console.log(`   Skipped: ${skipped}`);
    console.log(`   Total: ${links.length}`);

    if (errors.length > 0) {
      console.log("\n⚠️  Errors encountered:");
      errors.slice(0, 10).forEach((e) => console.log(`   ${e}`));
      if (errors.length > 10) {
        console.log(`   ... and ${errors.length - 10} more`);
      }
    }

    if (linked > 0) {
      console.log(
        "\n✨ Students are now linked to groups! Attendance page should now show students.",
      );
    }
  } catch (error) {
    console.error("❌ Fatal error:", error);
    process.exit(1);
  } finally {
    await db.$disconnect();
  }
}

main();
